version: '3.8'

services:
  web:
    network_mode: "host"
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./instance:/app/instance:rw
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - FLASK_RUN_HOST=0.0.0.0
      # Ensure python doesn't buffer output so we see logs immediately
      - PYTHONUNBUFFERED=1
